defaults: &defaults
  working_directory: /tmp

version: 2

jobs:

  build:
    machine: true
    steps:
      - checkout
      - run: RUBY_IMAGE=ruby:2.5-alpine docker-compose build ruby_gem
      - run: RUBY_IMAGE=ruby:2.5-alpine docker-compose run ruby_gem rake test
      - run: RUBY_IMAGE=ruby:2.6-alpine docker-compose build ruby_gem
      - run: RUBY_IMAGE=ruby:2.6-alpine docker-compose run ruby_gem rake test
      - run: RUBY_IMAGE=ruby:2.7-alpine docker-compose build ruby_gem
      - run: RUBY_IMAGE=ruby:2.7-alpine docker-compose run ruby_gem rake test
      - run: gem install roro
      - run: roro generate::exposed ci
      - run: echo 'source roro/ci.env' >> $BASH_ENV"
      - run: setup_gem_credentials.sh
      - run: gem install gem-release
      # - run: gem release --key $RUBYGEMS_API_KEY
