version: 2.1

jobs:

  build:
    machine: true
    steps:
      - checkout
  
  test:
    machine: true
    steps:
      - checkout
      - run: RUBY_IMAGE=ruby:2.5-alpine docker-compose build ruby_gem
      - run: RUBY_IMAGE=ruby:2.5-alpine docker-compose run ruby_gem rake test
      - run: RUBY_IMAGE=ruby:2.6-alpine docker-compose build ruby_gem
      - run: RUBY_IMAGE=ruby:2.6-alpine docker-compose run ruby_gem rake test
      - run: RUBY_IMAGE=ruby:2.7-alpine docker-compose build ruby_gem
      - run: RUBY_IMAGE=ruby:2.7-alpine docker-compose run ruby_gem rake test    
  pre_release:
    machine: true
    steps:
      - checkout
      - run: gem install roro
      - run: roro generate::exposed ci
      - run: echo 'source roro/containers/ruby_image/ci.env' >> $BASH_ENV
      - run: gem install gem-release
      - run: "echo \"rubygems_api_key:: $RUBYGEMS_API_KEY\" > ~/.gem/credentials"
      - run: printenv RUBYGEMS_API_KEY
      - run: cat ~/.gem/credentials

      
  release:
    machine: true
    steps:
      - checkout
      - run: gem install roro
      - run: roro generate::exposed ci
      - run: echo 'source roro/containers/ruby_image/ci.env' >> $BASH_ENV
      - run: gem install gem-release
      - run: "echo \"rubygems_api_key: $RUBYGEMS_API_KEY\" > ~/.gem/credentials"
      - run: printenv RUBYGEMS_API_KEY
      - run: cat ~/.gem/credentials
      - run: chmod 0600 ~/.gem/credentials
      - run: gem release --key KEY
        
workflows:
  version: 2
    
  build-release: 
    jobs: 
      - build
      - pre_release:
          filters: 
            branches: 
              only: master    
      - release:
          filters: 
            branches: 
              only: release