version: 2.1

jobs:

  build:
    machine: true
    steps:
      - checkout
  
  test:
    machine: true
    steps:
      - checkout
      - run: RUBY_IMAGE=ruby:2.5-alpine docker-compose build ruby_gem
      - run: RUBY_IMAGE=ruby:2.5-alpine docker-compose run ruby_gem rake test
      - run: RUBY_IMAGE=ruby:2.6-alpine docker-compose build ruby_gem
      - run: RUBY_IMAGE=ruby:2.6-alpine docker-compose run ruby_gem rake test
      - run: RUBY_IMAGE=ruby:2.7-alpine docker-compose build ruby_gem
      - run: RUBY_IMAGE=ruby:2.7-alpine docker-compose run ruby_gem rake test    
      
  release:
    machine: true
    steps:
      - checkout
      - run: gem install roro
      - run: roro generate::exposed ci
      - run: echo 'source roro/containers/ruby_image/ci.env' >> $BASH_ENV
      - run: printenv RUBYGEMS_API_KEY
      - run: ./.circleci/setup-gem-credentials.sh
      - run: cat ~/.gem/credentials
      - run: gem release
        
workflows:
  version: 2
    
  build-release: 
    jobs: 
      - build
      - release:
          filters: 
            branches: 
              only: release